apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-{{.Chart.Name}}
  namespace: {{ .Values.global.namespace }}
spec:
  type: NodePort
  selector:
    app: {{.Release.Name}}-{{.Chart.Name}}
    namespace: {{ .Values.global.namespace }}
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500