apiVersion: apps/v1
kind: Deployment
metadata:
  name: in-memory-map-deployment-2
  labels:
    tier: in-memory-map
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 1
  template: 
    metadata:
      name: index.js
      labels:
        name: index2.js
        tier: frontend
    spec:
      containers:
      - name: javascript
        image: localhost:32000/in-memory-map:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 128Mi
            cpu: 1
          limits:
            memory: 128Mi
            cpu: 1
        env:
          - name : store
            value: '{"version":"1", "name env": "env:name", "title": "env:MY_POD_NAME"}'
          - name: name
            value: value
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name