apiVersion: v1
kind: Service
metadata:
  name: in-memory-map-service
spec:
  type: NodePort
  selector:
    name: index.js
      
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32001
