apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{include "selfhost-cloud.name" .}}-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "selfhost-cloud.name" . }}-sa
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: {{include "selfhost-cloud.name" .}}-cluster-role
  apiGroup: rbac.authorization.k8s.io
