apiVersion: v1
kind: Endpoints
metadata:
  name: {{include "selfhost-cloud.name" .}}-service-external
  namespace: {{ .Values.global.namespace }}
subsets:
  - addresses:
      - ip: 192.168.1.10
    ports:
      - port: 3001