apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{include "selfhost-cloud.name" .}}-sa-binding
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{include "selfhost-cloud.name" .}}-sa
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: {{include "selfhost-cloud.name" .}}-release-manager
  apiGroup: rbac.authorization.k8s.io