apiVersion: v1
kind: Service
metadata:
  name: {{include "selfhost-cloud.name" .}}-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: NodePort
  selector:
    app: {{include "selfhost-cloud.name" .}}
    namespace: {{ .Values.global.namespace }}
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30501