apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-{{.Chart.Name}}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-{{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{.Chart.Name}}
        namespace: {{ .Values.global.namespace }}
    spec:
      containers:
        - name: {{.Release.Name}}-{{.Chart.Name}}
          image: ngnix:latest