apiVersion: v1
kind: Service
metadata:
  name: {{include "selfhost-cloud.name" .}}-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: NodePort
  selector:
    app: {{include "selfhost-cloud.name" .}}
    namespace: {{ .Values.global.namespace }}
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500